onlyBuiltDependencies:
    - bufferutil
    - core-js
    - es5-ext
    - esbuild
    - eslint-nibble
    - msw
    - patchright
    - patchright-core
    - protobufjs
    - rolldown
    - sharp
    - sleep
    - unrs-resolver
    - utf-8-validate
    - vue-demi
    - workerd
    - wrangler

overrides:
    difflib: https://codeload.github.com/postlight/difflib.js/tar.gz/32e8e38c7fcd935241b9baab71bb432fd9b166ed
    es-set-tostringtag: npm:@nolyfill/es-set-tostringtag@^1
    google-play-scraper>got: ^14.6.4
    google-play-scraper>ramda: ^0.32.0
    google-play-scraper>tough-cookie: ^6.0.0
    hasown: npm:@nolyfill/hasown@^1
    is-core-module: npm:@nolyfill/is-core-module@^1
    request>form-data: ^2.5.5
    rss-parser@3.13.0>entities: ^7.0.0
    rss-parser@3.13.0>xml2js: ^0.6.2
    safe-buffer: npm:@nolyfill/safe-buffer@^1
    safer-buffer: npm:@nolyfill/safer-buffer@^1
    side-channel: npm:@nolyfill/side-channel@^1
    htmlparser2: <12.0.0

patchedDependencies:
    '@mswjs/interceptors@0.41.9': patches/@mswjs__interceptors@0.41.9.patch
    rss-parser@3.13.0: patches/rss-parser@3.13.0.patch
    teleproto@1.228.5: patches/teleproto@1.228.5.patch
